
//  
// This is autogenerated C/C++ header
//  
 
#define THINX_ALIAS "robodyn-d1-mini"
#define THINX_API_KEY "88eb20839c1d8bf43819818b75a25cef3244c28e77817386b7b73b043193cef4"
#define THINX_API_PORT 7442
#define THINX_APP_VERSION "1.0.0"
#define THINX_AUTO_UPDATE true
#define THINX_CLOUD_URL "thinx.cloud"
#define THINX_COMMIT_ID "269c6fa21cf7e02d7db098b1fc20d14b9c8ce600"
#define THINX_FIRMWARE_VERSION "thinx-firmware-esp8266-1.6.92:2017-06-25"
#define THINX_FIRMWARE_VERSION_SHORT "1.6.92"
#define THINX_MQTT_PORT 1883
#define THINX_MQTT_URL "rtm.thinx.cloud"
#define THINX_OWNER "cedc16bb6bb06daaa3ff6d30666d91aacd6e3efbf9abbc151b4dcade59af7c12"
#define THINX_PLATFORM "platformio"
#define THINX_PROXY "thinx.local"
#define THINX_UDID "f8e88e40-43c8-11e7-9ad3-b7281c2b9610"

 	
