#!/bin/bash

THINX_ROOT=/opt/thinx/thinx-device-api

# Sample data for testing only, should return error missing JSON
#JSON='builder.thinx.json'

# Sample repositories for testing only, should return error missing workdir
#WORKDIR=/Users/sychram/Repositories/thinx-firmware-esp8266-ino
#WORKDIR=/Users/sychram/Repositories/thinx-firmware-esp8266-mos
#WORKDIR=/Users/sychram/Repositories/thinx-firmware-esp8266-lua
#WORKDIR=/Users/sychram/Repositories/thinx-firmware-esp8266-pio
#WORKDIR=/Users/sychram/Repositories/thinx-firmware-esp8266-upy

for i in "$@"
do
case $i in
	  -j*|--json=*)
      JSON="${i#*=}"
    ;;
    -r=*|--root=*)
      THINX_ROOT="${i#*=}"
      echo "Setting THINX_ROOT to $THINX_ROOT"
    ;;
    -w=*|--workdir=*)
      WORKDIR="${i#*=}"
    ;;
    *)
      # unknown option
    ;;
esac
done

if [[ ! -d "${WORKDIR}" ]]; then
	echo "--workdir= must be set"
	exit 1
fi

if [[ ! -f $JSON ]]; then
	echo "--json= must be set"
	exit 1
fi

# cleanup mess
if [[ -f ${WORKDIR}/.development ]]; then
  rm -rf ${WORKDIR}/.development
fi

source "$THINX_ROOT/infer"

echo
echo "Generating THiNX header, injecting environment variables from ${JSON}"
echo

generate_thinx_file ${WORKDIR} ${JSON}

echo

PLATFORM=$(infer_platform $WORKDIR)
echo "[pre-builder] platform: ${PLATFORM}"
PLATFORM_LANG=$(language_for_platform $PLATFORM)
echo "[pre-builder] language: ${PLATFORM_LANG}"

bash $THINX_ROOT/linter --language=${PLATFORM_LANG} --workdir=${WORKDIR}

exit 0
