#!/bin/bash

# private registry support

if [ -z ${DOCKER_REGISTRY} ]; then
    echo "DOCKER_REGISTRY variable must be set"
    exit 1
fi

docker image prune --force

docker pull ${DOCKER_REGISTRY}/thinx/transformer
docker pull ${DOCKER_REGISTRY}/thinx/redis
docker pull ${DOCKER_REGISTRY}/thinx/console
docker pull ${DOCKER_REGISTRY}/thinx/api
