version: "3"

services:

  redis:
    image: redis:5-alpine
    volumes:
      - redisdata:/data

  mosquitto:
    image: iegomez/mosquitto-go-auth:latest
    volumes:
      - ./conf:/etc/mosquitto
    ports:
      - 1883:1883

volumes:
  redisdata:
